CREATE TABLE [dbo].[Asset]
(
	[Id] UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL PRIMARY KEY, 
    [Name] NVARCHAR(200) NOT NULL, 
    [CurrencyId] UNIQUEIDENTIFIER NOT NULL, 
    [IsActive] BIT NOT NULL DEFAULT 1, 
    CONSTRAINT [FK_Asset_Currency] FOREIGN KEY ([CurrencyId]) REFERENCES [Currency]([Id])
)
